org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx1024m -XX:+UseSerialGC
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.caching=true
org.gradle.configureondemand=true
android.enableJetifier=true
android.useAndroidX=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
org.gradle.jvm.toolchain.install=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
kotlin.incremental=true
android.enableBuildCache=true
kapt.incremental.apt=true