#!/usr/bin/env python3
"""
setup_signing.py — Codemagic pre-build signing setup for wallet-tethrus (native Android).

Reads Codemagic environment variables:
  CM_KEYSTORE           Base64-encoded release keystore (.jks / .keystore)
  CM_KEYSTORE_PASSWORD  Password for the keystore file
  CM_KEY_ALIAS          Key alias inside the keystore
  CM_KEY_PASSWORD       Password for the private key

Writes:
  <repo_root>/keystore.jks      Decoded keystore binary
  <repo_root>/keys.properties   Gradle signing properties consumed by mbw/build.gradle

The signing config in mbw/build.gradle resolves the keystore as:
  storeFile file('../' + prodKeyStore)
So 'prodKeyStore=keystore.jks' resolves to <repo_root>/keystore.jks correctly.
"""

import base64
import logging
import os
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
KEYSTORE_PATH = REPO_ROOT / "keystore.jks"
KEY_PROPERTIES_PATH = REPO_ROOT / "keys.properties"

# ---------------------------------------------------------------------------
# Required environment variables
# ---------------------------------------------------------------------------
REQUIRED_ENV_VARS = [
    "CM_KEYSTORE",
    "CM_KEYSTORE_PASSWORD",
    "CM_KEY_ALIAS",
    "CM_KEY_PASSWORD",
]


def require_env(name: str) -> str:
    """Return the value of an environment variable or exit with an error."""
    value = os.environ.get(name, "").strip()
    if not value:
        log.error(
            "Required environment variable '%s' is missing or empty. "
            "Add it in the Codemagic UI under Environment Variables.",
            name,
        )
        sys.exit(1)
    return value


def decode_keystore(b64_keystore: str, dest: Path) -> None:
    """Decode a base64-encoded keystore and write it to *dest*."""
    log.info("Decoding keystore to: %s", dest)
    try:
        keystore_bytes = base64.b64decode(b64_keystore)
    except Exception as exc:  # noqa: BLE001
        log.error("Failed to base64-decode CM_KEYSTORE: %s", exc)
        sys.exit(1)

    try:
        dest.write_bytes(keystore_bytes)
    except OSError as exc:
        log.error("Failed to write keystore file '%s': %s", dest, exc)
        sys.exit(1)

    log.info("Keystore written (%d bytes).", len(keystore_bytes))


def write_key_properties(
    keystore_filename: str,
    keystore_password: str,
    key_alias: str,
    key_password: str,
    dest: Path,
) -> None:
    """Write the Gradle keys.properties file consumed by root build.gradle."""
    log.info("Writing signing properties to: %s", dest)
    content = (
        "# Auto-generated by scripts/setup_signing.py — do not edit manually.\n"
        "# This file is gitignored; it is recreated on every Codemagic build.\n"
        f"prodKeyStore={keystore_filename}\n"
        f"prodKeyAlias={key_alias}\n"
        f"prodKeyStorePassword={keystore_password}\n"
        f"prodKeyAliasPassword={key_password}\n"
        f"testKeyStore={keystore_filename}\n"
        f"testKeyAlias={key_alias}\n"
        f"testKeyStorePassword={keystore_password}\n"
        f"testKeyAliasPassword={key_password}\n"
    )
    try:
        dest.write_text(content, encoding="utf-8")
    except OSError as exc:
        log.error("Failed to write '%s': %s", dest, exc)
        sys.exit(1)
    log.info("keys.properties written.")


def validate_keystore(keystore_path: Path, keystore_password: str, key_alias: str) -> None:
    """Run keytool -list to verify the keystore is readable and the alias exists."""
    log.info("Validating keystore with keytool…")
    keytool_candidates = ["keytool"]
    java_home = os.environ.get("JAVA_HOME")
    if java_home:
        keytool_candidates.insert(0, str(Path(java_home) / "bin" / "keytool"))

    keytool_bin = None
    for candidate in keytool_candidates:
        try:
            subprocess.run(
                [candidate, "-help"],
                check=False,
                capture_output=True,
            )
            keytool_bin = candidate
            break
        except FileNotFoundError:
            continue

    if keytool_bin is None:
        log.warning(
            "keytool not found on PATH — skipping keystore validation. "
            "Ensure JDK 17 is installed in the Codemagic environment."
        )
        return

    cmd = [
        keytool_bin,
        "-list",
        "-v",
        "-keystore", str(keystore_path),
        "-storepass", keystore_password,
        "-alias", key_alias,
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except subprocess.TimeoutExpired:
        log.error("keytool validation timed out after 30 seconds.")
        sys.exit(1)
    except Exception as exc:  # noqa: BLE001
        log.error("keytool execution failed: %s", exc)
        sys.exit(1)

    if result.returncode != 0:
        log.error(
            "keytool -list failed (exit %d).\nstdout: %s\nstderr: %s",
            result.returncode,
            result.stdout,
            result.stderr,
        )
        sys.exit(1)

    log.info("Keystore validation passed.")
    # Print the certificate fingerprint for audit trail
    for line in result.stdout.splitlines():
        if "SHA" in line or "Certificate" in line or "Alias" in line:
            log.info("  %s", line.strip())


def main() -> None:
    log.info("=== Codemagic signing setup — wallet-tethrus ===")
    log.info("Repo root: %s", REPO_ROOT)

    # 1. Read all required env vars (exits on any missing)
    env = {var: require_env(var) for var in REQUIRED_ENV_VARS}

    keystore_b64 = env["CM_KEYSTORE"]
    keystore_password = env["CM_KEYSTORE_PASSWORD"]
    key_alias = env["CM_KEY_ALIAS"]
    key_password = env["CM_KEY_PASSWORD"]

    # 2. Decode and write keystore
    decode_keystore(keystore_b64, KEYSTORE_PATH)

    # 3. Validate the keystore
    validate_keystore(KEYSTORE_PATH, keystore_password, key_alias)

    # 4. Write keys.properties
    write_key_properties(
        keystore_filename=KEYSTORE_PATH.name,   # "keystore.jks"
        keystore_password=keystore_password,
        key_alias=key_alias,
        key_password=key_password,
        dest=KEY_PROPERTIES_PATH,
    )

    log.info("=== Signing setup complete. Build can proceed. ===")


if __name__ == "__main__":
    main()
